FORMAT: 1A

# tardis-api
API for [tardis](http://github.com/kiplic/tardis). Built with express, redis, and mongo.

## Courses Collection [/notes]
### List all Courses [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "CS 1110", "description": "Introduction to Programming"
        }, {
          "id": 2, "name": "CS 2110", "description": "Software Development Methods"
        }]

### Create a Course [POST]
+ Request (application/json)

        { "name": "CS 1110", "description": "Introduction to Programming" }

+ Response 201 (application/json)

        { "id": 1, "name": "CS 1110", "description": "Introduction to Programming" }

## Course [/courses/{id}]
A single Course object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Course to perform action with. Has example value.

### Retrieve a Course [GET]
+ Response 200 (application/json)

        { "id": 1, "name": "CS 1110", "description": "Introduction to Programming" }

### Remove a Course [DELETE]
+ Response 204


## Queues by Course Collection [/courses/{id}/queues]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Course to perform action with. Has example value.
    
### List all Queues by Course [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "CS 1110", "description": "Introduction to Programming"
        }, {
          "id": 2, "name": "CS 2110", "description": "Software Development Methods"
        }]
        
### Create a Queue for a Course [POST]
+ Request (application/json)

        { "name": "Wednesday Night Office Hours" }

+ Response 201 (application/json)

        { "id" : "1", "name": "Wednesday Night Office Hours" }
        
## Queues Collection [/queues]

### List all Queues [GET]

+ Response 200 (application/json)

        [{ 
            "id" : "1", "name": "Wednesday Night Office Hours"
        }, {
            "id" : "2", "name": "Thursday Night Office Hours"
        }]